version: '3.3'

services:
  adminer:
    image: adminer
    container_name: "${__DOCKER_SERVICE_PREFIX__}_adminer"
    hostname: "${__DOCKER_SERVICE_PREFIX__}_adminer"
    ports:
      - ${ADMINER_PORT}:8080
