version: '3.3'

services:
  es:
    container_name: "${__DOCKER_SERVICE_PREFIX__}_es"
    hostname: "${__DOCKER_SERVICE_PREFIX__}_es"
    image: 'elasticsearch:5.5.2-alpine'
    volumes:
      - '${__DOCKER_PATH__}/elasticsearch:/usr/share/elasticsearch/data'
    ports:
      - ${ELASTIC_SEARCH_PORT}:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9200"]
      interval: 10s
      timeout:  10s
      retries:  30
