version: '3.3'

services:
  es:
    container_name: "work_${ENV}_es"
    hostname: "work_${ENV}_es"
    image: 'elasticsearch:5.5.2-alpine'
    volumes:
      - '${ENVROOT}/proc/docker/${ENV}/elasticsearch:/usr/share/elasticsearch/data'
    ports:
      - '9400:9200'
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9200"]
      interval: 10s
      timeout:  10s
      retries:  30
