version: '3.3'

services:
  mailhog:
    container_name: "work_${ENV}_mailhog"
    hostname: "work_${ENV}_mailhog"
    image: mailhog/mailhog:v1.0.0
    command: ['-storage=maildir', '-maildir-path=/maildir']
    volumes:
      - '${__var_mail_dir__}/mailhog/${ENV}:/maildir'
    ports:
      - '8025:8025'
      - '1025:1025'
