version: '3.3'

services:
  mailhog:
    container_name: "${__DOCKER_SERVICE_PREFIX__}_mailhog"
    hostname: "${__DOCKER_SERVICE_PREFIX__}_mailhog"
    image: mailhog/mailhog:v1.0.0
    command: ['-storage=maildir', '-maildir-path=/maildir']
    volumes:
      - '${__VAR_MAIL_DIR__}/mailhog/${__PROFILE__}:/maildir'
    ports:
      - '8025:8025'
      - '1025:1025'
