version: '3.3'

services:
  mysql57:
    container_name: "${__DOCKER_SERVICE_PREFIX__}_mysql57"
    hostname: "${__DOCKER_SERVICE_PREFIX__}_mysql57"
    image: mysql:5.7
    volumes:
      - '${__DOCKER_PATH__}/mysql57:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workspace
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - ${MYSQL57_PORT}:3306
