version: '3.3'

services:
  mysql:
    container_name: "work_${ENV}_mysql"
    hostname: "work_${ENV}_mysql"
    image: mysql
    volumes:
      - '${ENVROOT}/proc/docker/${ENV}/mysql:/var/lib/mysql'
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: workspace
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - ${MYSQL_PORT}:3306
