version: '3.3'

services:
  mysql:
    container_name: "${__DOCKER_SERVICE_PREFIX__}_mysql"
    hostname: "${__DOCKER_SERVICE_PREFIX__}_mysql"
    image: mysql
    volumes:
      - '${__DOCKER_PATH__}/mysql:/var/lib/mysql'
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: workspace
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - ${MYSQL_PORT}:3306
