version: '3.3'

services:
  postgresql:
    container_name: "${__DOCKER_SERVICE_PREFIX__}_postgresql"
    hostname: "${__DOCKER_SERVICE_PREFIX__}_postgresql"
    image: postgres
    volumes:
      - '${__DOCKER_PATH__}/postgresql:/var/lib/postgresql/data'
    restart: always
    environment:
      POSTGRES_DB: workspace
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - ${POSTGRESQL_PORT}:5432
