version: '3.3'

services:
  queue:
    container_name: "work_${ENV}_queue"
    image: 'rabbitmq:3-management'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - '${ENVROOT}/proc/docker/${ENV}/rabbitmq:/var/lib/rabbitmq'
    ports: ['5672:5672', '15672:15672']
    healthcheck:
      test: ["CMD", "rabbitmqadmin", "show", "overview", "-u", "admin", "-p", "admin"]
      interval: 10s
      timeout:  10s
      retries:  30
