version: '3.3'

services:
  redis:
    container_name: "${__DOCKER_SERVICE_PREFIX__}_redis"
    hostname: "${__DOCKER_SERVICE_PREFIX__}_redis"
    image: redis:4-alpine
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - '${__DOCKER_PATH__}/redis:/var/lib/redis/'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout:  10s
      retries:  30
