version: '3.3'

services:
  redis-commander:
    container_name: "${__DOCKER_SERVICE_PREFIX__}_redis_commander"
    hostname: "${__DOCKER_SERVICE_PREFIX__}_redis_commander"
    image: rediscommander/redis-commander:latest
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - ${REDIS_COMMANDER_PORT}:8081
