version: '3.3'

services:
  redis:
    container_name: "work_${ENV}_redis"
    hostname: "work_${ENV}_redis"
    image: redis:4-alpine
    ports:
      - '6379:6379'
    volumes:
      - '${ENVROOT}/proc/docker/${ENV}/redis:/var/lib/redis/'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout:  10s
      retries:  30
