version: '3.3'

services:
  mysql:
    container_name: "work_${ENV}_mysql"
    hostname: "work_${ENV}_mysql"
    image: mysql:5.7
    volumes:
      - '../../docker/run/env/${ENV}/mysql:/var/lib/mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workspace
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306
