version: '3.3'

services:
  redis:
    image: redis:4-alpine
    ports:
      - '6379:6379'
    volumes:
      - '../../docker/run/redis:/data'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout:  10s
      retries:  30
